package com.tm.jdbc.dbtype;

public class ColumnDescriptor {
	
	private String name;
	private DataType dataType;
	private boolean required;
	private boolean autogenerated;
	
	public ColumnDescriptor(String name, DataType dataType) {
		this(name, dataType, false, false);
	}
	
	public ColumnDescriptor(String name, DataType dataType, boolean required) {
		this(name, dataType, required, false);
	}
	
	public ColumnDescriptor(String name, DataType dataType, boolean required,
			boolean autogenerated) {
		super();
		this.name = name;
		this.dataType = dataType;
		this.required = required;
		this.autogenerated = autogenerated;
	}

	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public DataType getDataType() {
		return dataType;
	}
	
	public void setDataType(DataType dataType) {
		this.dataType = dataType;
	}
	
	public boolean isRequired() {
		return required;
	}
	
	public void setRequired(boolean required) {
		this.required = required;
	}
	
	public boolean isAutogenerated() {
		return autogenerated;
	}
	
	public void setAutogenerated(boolean autogenerated) {
		this.autogenerated = autogenerated;
	}
	
	

}
